[build]
builder = "NIXPACKS"

[deploy]
startCommand = "http-server public -p 3000 -c-1"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[[services]]
name = "studentregister"

[services.variables]
PORT = "3000"
